### ISSUE TITLE
The script in step 2 does not work

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/MIMDocs#174]
@wsy commented on [Mon Jul 29 2019](https://github.com/MicrosoftDocs/MIMDocs.zh-cn/issues/18)

In line 3 of the script and line 6 of the script in Step 2, you created two AdUser with same name MIMMA.
```Powershell
New-ADUser -SamAccountName MIMINSTALL -name MIMMA
New-ADUser -SamAccountName MIMMA -name MIMMA
```
Also, if you copy and paste. this script to Powershell, you will find another similar error.
I believe these two low level errors can be prevented if the author verified his/her document by setting up a sample environment with the steps and sample scripts in this document.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b63b3e40-9767-a459-3c57-3aad83026b74
* Version Independent ID: d1cf0874-08cc-4c70-44d5-a1a625bdfe42
* Content: [设置 Microsoft Identity Manager 2016 的域](https://docs.microsoft.com/zh-cn/microsoft-identity-manager/preparing-domain#feedback)
* Content Source: [MIMDocs/preparing-domain.md](https://github.com/MicrosoftDocs/MIMDocs.zh-cn/blob/live/MIMDocs/preparing-domain.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

---

@wsy commented on [Mon Jul 29 2019](https://github.com/MicrosoftDocs/MIMDocs.zh-cn/issues/18#issuecomment-515870371)

https://github.com/MicrosoftDocs/MIMDocs/issues/103
So I found out this link. This issue has been here since July 2018.

---

@srvbpigh commented on [Mon Jul 29 2019](https://github.com/MicrosoftDocs/MIMDocs.zh-cn/issues/18#issuecomment-515870830)

Hello, @wsy
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since it's about the original documentation
It also looks like it was previously logged
best

**Comment by wsy** [comment]
Yes, this is same issue with [Issue#103](https://github.com/MicrosoftDocs/MIMDocs/issues/103) which was opened 12 months ago.
Sorry for this duplicate.
Because I was reading documents in zh-cn site, so I did not see any opened issues. That's why I opened Issue#18 in another repo(MIMDocs.zh-cn).
Then I realized that repo was just a translation, so I came to this repo and saw that duplicated issue opened July 2018.

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close

**Comment by wsy** [comment]
> The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.
> 
> #please-close

Hi @billmath ,
In your documents, a lot of code has this issue where dash "-" became "–".
Because of this, if a user copy code from your example, and paste it to terminal, it will not work.
Below is a incomplete table of markdown files containing such code:
|File|
|:---:|
|pam/deploy-pam-with-windows-server-2016.md|
|pam/step-1-prepare-corp-domain.md|
|pam/step-2-prepare-priv-domain-controller.md|
|pam/step-3-prepare-pam-server.md|
|pam/step-6-transition-group-to-pam.md|
|pam/step-7-elevate-user-access.md|
|prepare-server-ws2012r2.md|

I used command `grep --color=always -rn –w *` in WSL.
![image](https://github.com/MicrosoftDocs/MIMDocs/assets/2684991/daae6409-5312-4ad8-8c59-5da63f73b303)
